name: Build

on:
    workflow_call:
        inputs:
            artifact-suffix:
                required: true
                type: string

jobs:
    build:
        name: Build
        runs-on: windows-latest
        env:
            RimWorldSteamWorkshopFolderPath: ..\.deps\refs
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Upload Mod Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Rimthem-${{ inputs.artifact-suffix }}
                  path: |
                      About/
                      Common/
                      LICENSE
                      LICENSE.Apache-2.0
                      LICENSE.MIT
                      README.md
                      CHANGELOG.md
                      LoadFolders.xml
                      !**/.*
                      !About/*.pdn
                      !About/*.svg
                      !About/*.ttf
